algoritmo "Primeiro algoritmo"
var
 nome: caractere 
 n1: inteiro
 n2: inteiro
 soma: inteiro
 
inicio
   escreval ("Olá seja bem vindo ao primeiro algoritmo, vamos começar com seu nome:")
   leia (nome)
   escreval ("Ok ", nome, " agora digite o primeiro número:")
   leia (n1)
   escreval ("Agora digite o segundo número:")
   leia (n2)
   soma = n1 + n2
   escreval ("A soma dos números é: ", soma)
fimalgoritmo